# Learning Numpy

In [266]:
import numpy as np

### Creating Arrays

<strong><ins>All arrays mentioned here are numpy arrays as long as opposite is not mentioned</ins></strong> please solve the problems with this knowledge.

Create an array in size of 4*3 and assing it to arr variable

In [267]:
arr = np.array([1,2,3,4,5])
arr.resize(4,3)
arr

array([[1, 2, 3],
       [4, 5, 0],
       [0, 0, 0],
       [0, 0, 0]])

Create an array with elements from 0 to 15 (both inclusive) and assing it to arr2 variable   
Then print the shape of the arr2  
copy the arr2 to arr2_copy  
print arr2, arr2_copy   
Change its shape to 4*4 and assign to itself   
print arr2, arr2_copy again    

In [268]:
arr2 =np.arange(15+1)
print(arr2.shape)

# print(arr2, arr2_copy)
# arr2_copy=arr2_copy.reshape(4,4)
# print(arr2)
# print(arr2_copy)

(16,)


In [269]:
arr2_copy = arr2.copy()
print(arr2_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [270]:
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [271]:
arr2 = arr2.reshape(4,4)

In [272]:
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [273]:
print(arr2_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### Some Functions 

##### How many dimentions there are in arr2 variable? 

In [274]:
arr2.ndim

2

##### Describe the number of rows and columns in arr2 variable 

In [275]:
arr2.shape

(4, 4)

##### How many elements there are in arr2 variable?

In [276]:
arr2.size

16

##### Print the data type of arr2

In [277]:
arr2.dtype

dtype('int32')

#### Print the data location in the memory


In [ ]:
arr2.data

### Some Statistics About the Arrays

#### Show 50th percentile of arr2

In [ ]:
np.percentile(arr2, 50)

#### Show mean of arr2 elements

In [ ]:
np.mean(arr2)

#### Show median of arr2 elements

In [ ]:
np.median(arr2)

##### Create one dimensional normally distrubuted array with mean 3 standard deviation is 4 and has elements of 100

In [ ]:
from numpy import random

In [ ]:
s = np.random.normal(loc=3, scale=4, size=100)

#### Install matplotlib library for ploting purposes and then plot the s 
- search to find how to do

In [ ]:
import matplotlib.pyplot as plt
plt.hist(s)
plt.show()

____

# Learning Pandas

##### Read the airline safety data assign to df variable and print first 5 rows with pandas function

In [1]:
import pandas as pd 

In [2]:
df = pd.read_table('https://raw.githubusercontent.com/fivethirtyeight/data/master/airline-safety/airline-safety.csv', sep=',')

In [ ]:
df.head()

##### print last 5 rows with pandas function

In [ ]:
df.tail()

##### Show shape of df

In [ ]:
df.shape

##### Show descriptive statistics of df

In [ ]:
df.describe()

#### Show df column informations

In [ ]:
df.info()

#### Select companies and incidents_85_99 with incidents_85_99 is less than 10

In [ ]:
df[df.incidents_85_99 < 10][['airline','incidents_85_99']]

#### Group companies by first letter(lower) and take the mean incidents_85_99 and make it a dataframe again 

In [6]:
(df.assign(
    airline_fist_letter = df['airline'].str.lower().str[0:1])
    .groupby(['airline_fist_letter'] )['incidents_85_99'].mean()
    .to_frame('incidents_85_99').reset_index()
)

airline_fist_letter  incidents_85_99
0                    a        10.714286
1                    b         4.000000
2                    c         4.250000
3                    d        24.000000
4                    e        11.333333
5                    f         1.000000
6                    g         5.500000
7                    h         0.000000
8                    i         4.000000
9                    j         3.000000
10                   k         7.000000
11                   l         4.500000
12                   m         3.000000
13                   p         7.500000
14                   q         1.000000
15                   r         5.000000
16                   s         3.000000
17                   t         5.400000
18                   u        17.500000
19                   v         4.000000
20                   x         9.000000